/** Maps admin language codes to Google Translate API codes (mirrors backend). */
const TRANSLATE_LANGUAGE_CODE_MAP = {
  zn: "zh-CN",
  zh: "zh-CN",
  "zh-cn": "zh-CN",
  "zh-tw": "zh-TW",
  cn: "zh-CN",
  chinese: "zh-CN",
  mandarin: "zh-CN",
  hindi: "hi",
  hi: "hi",
  ta: "ta",
  tamil: "ta",
  te: "te",
  telugu: "te",
  bn: "bn",
  bengali: "bn",
  mr: "mr",
  marathi: "mr",
  gu: "gu",
  gujarati: "gu",
  kn: "kn",
  kannada: "kn",
  ml: "ml",
  malayalam: "ml",
  pa: "pa",
  punjabi: "pa",
  ur: "ur",
  urdu: "ur",
  ja: "ja",
  japanese: "ja",
  ko: "ko",
  korean: "ko",
  ar: "ar",
  arabic: "ar",
  es: "es",
  spanish: "es",
  fr: "fr",
  french: "fr",
  de: "de",
  german: "de",
  pt: "pt",
  "pt-br": "pt",
  portuguese: "pt",
  it: "it",
  italian: "it",
  ru: "ru",
  russian: "ru",
  he: "iw",
  jw: "jv",
  in: "id",
  indonesian: "id",
  nb: "no",
  no: "no",
  norwegian: "no",
};

export function toTranslateLanguageCode(code) {
  const normalized = (code || "en").toLowerCase().trim().replace(/_/g, "-");
  if (!normalized) return "en";
  return TRANSLATE_LANGUAGE_CODE_MAP[normalized] || normalized.split("-")[0];
}
