"use client";

import React from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Edit, Trash2, Sparkles, Search } from "lucide-react";

/** Normalize one option to { text, explanation } from API (may use text/value/option/label, explanation/reason/desc). */
function normalizeOption(o) {
  if (o == null) return { text: "", explanation: "" };
  if (typeof o !== "object") return { text: String(o), explanation: "" };
  const text = (o.text ?? o.value ?? o.option ?? o.label ?? "").trim();
  const explanation = (o.explanation ?? o.reason ?? o.desc ?? "").trim();
  return { text: text || "", explanation: explanation || "" };
}

/** Build options array for display: prefer flattened option1..option4 from API so all columns show data. */
function getDisplayOptions(q) {
  const flattened = [];
  for (let i = 1; i <= 4; i++) {
    const text = (q[`option${i}`] ?? "").trim();
    const explanation = (q[`option${i}_explanation`] ?? "").trim();
    flattened.push({ text: text || "", explanation: explanation || "" });
  }
  const fromArray = (q.options || []).map(normalizeOption);
  if (fromArray.length >= 4 || fromArray.some((o) => o.text || o.explanation)) {
    const merged = flattened.map((f, i) => {
      const a = fromArray[i];
      if (a && (a.text || a.explanation)) return a;
      return f;
    });
    while (merged.length < 4) merged.push({ text: "", explanation: "" });
    return merged.slice(0, Math.max(4, merged.length));
  }
  return flattened;
}

function matchesSearch(q, search) {
  const s = (search || "").toLowerCase();
  if (!s) return true;
  if ((q.question_text || "").toLowerCase().includes(s)) return true;
  for (let i = 1; i <= 4; i++) {
    if ((q[`option${i}`] || "").toLowerCase().includes(s)) return true;
    if ((q[`option${i}_explanation`] || "").toLowerCase().includes(s)) return true;
  }
  for (const o of q.options || []) {
    const { text } = normalizeOption(o);
    if (text.toLowerCase().includes(s)) return true;
  }
  for (const a of q.correct_answers || []) {
    if (String(a).toLowerCase().includes(s)) return true;
  }
  if ((q.explanation || "").toLowerCase().includes(s)) return true;
  return false;
}

export default function GeneratedQuestionsTab({
  generatedQuestions,
  generatedLoading,
  loading,
  selectedGeneratedIds,
  toggleSelectGenerated,
  toggleSelectAllGenerated,
  toggleSelectAllGeneratedFiltered,
  setShowBulkDeleteGeneratedConfirm,
  openEditGenerated,
  openDeleteGenerated,
  handleValidateWithGemini,
  searchQuery,
  onSearchChange,
}) {
  const filtered = !searchQuery?.trim() ? generatedQuestions : generatedQuestions.filter((q) => matchesSearch(q, searchQuery));
  const maxOpts = generatedQuestions.length
    ? Math.max(4, ...generatedQuestions.map((q) => (q.options || []).length))
    : 4;

  /** Show correct answer as option numbers. Use backend-computed correct_answer_numbers when present (from OpenAI). */
  function getCorrectAnswerDisplay(q) {
    // q.correct_answer_numbers is now an array of integers
    const numbers = q.correct_answer_numbers || [];
    if (numbers.length > 0) {
      return numbers.join(", "); // shows "2, 3"
      
      // Optional: map to letters A, B, C, D
      // const letters = ["A","B","C","D","E","F"];
      // return numbers.map(n => letters[n-1]).join(", ");
    }
  
    // fallback to correct_answers text if numbers missing  
    const correct = q.correct_answers || [];
    if (correct.length === 0) return "—";
    return correct.map((c) => String(c).trim()).filter(Boolean).join(", ") || "—";
  }
  

  /** Question Type: use API value when present, else derive from correct_answers length */
  function getQuestionType(q) {
    if (q.question_type === "single-correct" || q.question_type === "multiple-correct") return q.question_type;
    const n = (q.correct_answers || []).length;
    return n <= 1 ? "single-correct" : "multiple-correct";
  }

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-4">
        <div>
          <CardTitle>Generated Questions {generatedQuestions.length > 0 ? `(${generatedQuestions.length})` : ""}</CardTitle>
          <p className="text-sm text-gray-500 mt-1">
            Questions generated by OpenAI. Each has options with explanations, correct answers, and overall explanation. Count matches the uploaded document.
          </p>
        </div>
        <div className="flex gap-2 shrink-0 flex-wrap">
          <Button
            variant="outline"
            className="text-red-600 hover:text-red-700 hover:bg-red-50"
            disabled={selectedGeneratedIds.size === 0}
            onClick={() => setShowBulkDeleteGeneratedConfirm(true)}
          >
            <Trash2 className="w-4 h-4 mr-2" /> Bulk Delete {selectedGeneratedIds.size ? `(${selectedGeneratedIds.size})` : ""}
          </Button>
          <Button
            variant="default"
            onClick={handleValidateWithGemini}
            disabled={loading || generatedQuestions.length === 0}
          >
            <Sparkles className="w-4 h-4 mr-2" /> Validate with Gemini AI
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        {generatedQuestions.length > 0 && (
          <div className="mb-4 flex items-center gap-2">
            <Search className="h-4 w-4 text-gray-500" />
            <Input
              placeholder="Search by question, options, answers, explanation..."
              value={searchQuery || ""}
              onChange={(e) => onSearchChange(e.target.value)}
              className="max-w-sm"
            />
          </div>
        )}
        {generatedLoading ? (
          <p className="text-gray-500">Loading...</p>
        ) : generatedQuestions.length === 0 ? (
          <p className="text-gray-500">No generated questions yet. Use Generate New Questions from Input Questions tab.</p>
        ) : filtered.length === 0 ? (
          <p className="text-gray-500">No questions match your search.</p>
        ) : (
          <div className="rounded-md border overflow-x-auto">
            <table className="w-full text-sm min-w-[1000px]">
              <thead>
                <tr className="border-b bg-gray-50">
                  <th className="text-left font-medium p-3 w-10">
                    <input
                      type="checkbox"
                      checked={filtered.length > 0 && filtered.every((q) => q.id && selectedGeneratedIds.has(q.id))}
                      onChange={() => (toggleSelectAllGeneratedFiltered ? toggleSelectAllGeneratedFiltered(filtered.map((q) => q.id).filter(Boolean)) : toggleSelectAllGenerated())}
                      className="rounded"
                    />
                  </th>
                  <th className="text-left font-medium p-3 w-12">#</th>
                  <th className="text-left font-medium p-3 min-w-[200px]">Question Text</th>
                  <th className="text-left font-medium p-3 w-36">Question Type</th>
                  {Array.from({ length: maxOpts }, (_, j) => (
                    <React.Fragment key={j}>
                      <th className="text-left font-medium p-3 min-w-[140px]">Option {j + 1}</th>
                      <th className="text-left font-medium p-3 min-w-[140px] text-gray-600">Option {j + 1} Explanation</th>
                    </React.Fragment>
                  ))}
                  <th className="text-left font-medium p-3 min-w-[100px]">Correct Answers</th>
                  <th className="text-left font-medium p-3 min-w-[200px]">Overall Explanation</th>
                  <th className="text-left font-medium p-3 w-36">Actions</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((q, i) => {
                  const opts = getDisplayOptions(q);
                  return (
                    <tr key={q.id || i} className="border-b last:border-0 hover:bg-gray-50/50">
                      <td className="p-3 align-top">
                        <input
                          type="checkbox"
                          checked={q.id ? selectedGeneratedIds.has(q.id) : false}
                          onChange={() => q.id && toggleSelectGenerated(q.id)}
                          className="rounded"
                        />
                      </td>
                      <td className="p-3 text-gray-600">{i + 1}</td>
                      <td className="p-3 text-gray-900 align-top">{q.question_text}</td>
                      <td className="p-3 align-top">
                        <span className="text-xs font-medium px-2 py-1 rounded bg-gray-100 text-gray-800">
                          {getQuestionType(q)}
                        </span>
                      </td>
                      {Array.from({ length: maxOpts }, (_, j) => (
                        <React.Fragment key={j}>
                          <td className="p-3 text-gray-800 align-top font-medium">
                            {opts[j] ? opts[j].text : ""}
                          </td>
                          <td className="p-3 text-gray-600 text-xs align-top italic">
                            {opts[j] ? opts[j].explanation : ""}
                          </td>
                        </React.Fragment>
                      ))}
                      <td className="p-3 text-gray-700 align-top font-medium">{getCorrectAnswerDisplay(q)}</td>
                      <td className="p-3 text-gray-600 text-sm align-top min-w-[200px] whitespace-pre-wrap">
                        {q.explanation != null && q.explanation !== "" ? q.explanation : "—"}
                      </td>
                      <td className="p-3 align-top">
                        <div className="flex gap-2">
                          <Button variant="outline" size="sm" onClick={() => openEditGenerated(q)}>
                            <Edit className="w-4 h-4 mr-1" /> Edit
                          </Button>
                          <Button
                            variant="outline"
                            size="sm"
                            className="text-red-600 hover:text-red-700"
                            onClick={() => openDeleteGenerated(q.id)}
                          >
                            <Trash2 className="w-4 h-4 mr-1" /> Delete
                          </Button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
